#!/bin/sh
# Enrols this computer as {{DEVICE_ID}} on the trusted Wi-Fi network.
#
# Generated by cert-enrolment. This script contains a single-use enrolment
# token that expires ten minutes after it was downloaded. Run it once, as
# root, on the computer being enrolled:
#
#     sudo sh ./enrol-{{LABEL}}.sh
#
# It:
#   1. saves the network's Root CA
#   2. creates a private key readable only by root
#   3. obtains a device certificate for {{DEVICE_ID}}
#   4. adds a NetworkManager profile for the trusted network (EAP-TLS, TLS 1.3)
#   5. installs a systemd timer that renews the certificate
#
# Needs curl and openssl; NetworkManager and systemd are used when present.
# Files are kept in /etc/cert-enrolment.

set -eu

DEVICE_ID='{{DEVICE_ID}}'
CA_URL='{{CA_URL}}'
TOKEN='{{TOKEN}}'
SSID='{{SSID}}'
RADIUS_SERVER_NAME='{{RADIUS_SERVER_NAME}}'

DIR=/etc/cert-enrolment
RENEW=/usr/local/libexec/cert-enrolment-renew

step() { printf '==> %s\n' "$1"; }
fail() { printf 'error: %s\n' "$1" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || fail "run this script as root, for example: sudo sh $0"
for tool in curl openssl sed; do
    command -v "$tool" >/dev/null 2>&1 || fail "$tool is required"
done

umask 077
mkdir -p "$DIR"
chmod 700 "$DIR"

# 1. Root CA ------------------------------------------------------------------
step 'Saving the network Root CA'
cat > "$DIR/root-ca.crt" <<'PEM'
{{ROOT_CA_PEM}}
PEM
chmod 644 "$DIR/root-ca.crt"

# The renewal program. It is also used here for the first certificate,
# obtained with the enrolment token instead of the current certificate.
step 'Installing the renewal program'
mkdir -p "$(dirname "$RENEW")"
cat > "$RENEW" <<'RENEW'
#!/bin/sh
# Renews the cert-enrolment device certificate once two thirds of its
# lifetime has passed. Each renewal creates a new key (step-ca rekey),
# proving identity with the current certificate.
#
#   cert-enrolment-renew             renew if due
#   cert-enrolment-renew --token T   first enrolment with token T
set -eu
umask 077
DIR=/etc/cert-enrolment
. "$DIR/settings"

log() { printf '%s\n' "$1"; }

# Prints one string field of a JSON object, with its escapes resolved.
json_field() {
    value=$(sed -n "s/.*\"$1\":\"\\([^\"]*\\)\".*/\\1/p" "$2")
    printf '%b\n' "$value"
}

# PEM text as one JSON string.
json_pem() { awk 'BEGIN { ORS = "" } { printf "%s\\n", $0 }' "$1"; }

token=
if [ "${1:-}" = --token ]; then
    token=$2
elif [ -f "$DIR/cert.pem" ]; then
    now=$(date +%s)
    start=$(date -d "$(openssl x509 -in "$DIR/cert.pem" -noout -startdate | cut -d= -f2)" +%s)
    end=$(date -d "$(openssl x509 -in "$DIR/cert.pem" -noout -enddate | cut -d= -f2)" +%s)
    due=$((start + (end - start) * 2 / 3))
    if [ "$now" -ge "$end" ]; then
        log "The certificate expired; enrol this computer again."
        exit 1
    fi
    if [ "$now" -lt "$due" ]; then
        log "Valid until $(date -d "@$end"); renewal due $(date -d "@$due")."
        exit 0
    fi
else
    log "No certificate in $DIR; enrol this computer again."
    exit 1
fi

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out "$work/key.pem" 2>/dev/null
openssl req -new -key "$work/key.pem" -subj "/CN=$DEVICE_ID" \
    -addext "subjectAltName=DNS:$DEVICE_ID" -out "$work/request.csr" 2>/dev/null

if [ -n "$token" ]; then
    printf '{"csr":"%s","ott":"%s"}' "$(json_pem "$work/request.csr")" "$token" > "$work/request.json"
    status=$(curl -sS -o "$work/response.json" -w '%{http_code}' --cacert "$DIR/root-ca.crt" \
        -H 'Content-Type: application/json' --data @"$work/request.json" "$CA_URL/1.0/sign")
else
    printf '{"csr":"%s"}' "$(json_pem "$work/request.csr")" > "$work/request.json"
    status=$(curl -sS -o "$work/response.json" -w '%{http_code}' --cacert "$DIR/root-ca.crt" \
        --cert "$DIR/cert.pem" --key "$DIR/key.pem" \
        -H 'Content-Type: application/json' --data @"$work/request.json" "$CA_URL/1.0/rekey")
fi

if [ "$status" != 201 ]; then
    log "The certificate authority refused the request (HTTP $status): $(json_field message "$work/response.json")"
    exit 1
fi

json_field crt "$work/response.json" > "$work/cert.pem"
json_field ca "$work/response.json" >> "$work/cert.pem"
openssl x509 -in "$work/cert.pem" -noout 2>/dev/null || { log "The certificate authority returned no certificate."; exit 1; }

# Replace the key and certificate together.
mv "$work/key.pem" "$DIR/key.pem"
mv "$work/cert.pem" "$DIR/cert.pem"
chmod 600 "$DIR/key.pem" "$DIR/cert.pem"
log "Certificate for $DEVICE_ID valid until $(openssl x509 -in "$DIR/cert.pem" -noout -enddate | cut -d= -f2)."
RENEW
chmod 755 "$RENEW"

cat > "$DIR/settings" <<SETTINGS
DEVICE_ID='$DEVICE_ID'
CA_URL='$CA_URL'
SETTINGS

# 2 and 3. Key and certificate ----------------------------------------------------
step "Requesting a certificate for $DEVICE_ID"
"$RENEW" --token "$TOKEN" || fail "enrolment failed. Enrolment tokens work once and expire ten minutes after download; download a new script if needed."

# 4. Wi-Fi profile ----------------------------------------------------------------
if command -v nmcli >/dev/null 2>&1; then
    step "Adding the NetworkManager profile for $SSID"
    nmcli connection delete id "$SSID" >/dev/null 2>&1 || true
    nmcli connection add type wifi con-name "$SSID" ifname '*' ssid "$SSID" \
        wifi-sec.key-mgmt wpa-eap \
        wifi-sec.pmf optional \
        802-1x.eap tls \
        802-1x.identity "$DEVICE_ID" \
        802-1x.ca-cert "$DIR/root-ca.crt" \
        802-1x.client-cert "$DIR/cert.pem" \
        802-1x.private-key "$DIR/key.pem" \
        802-1x.private-key-password-flags not-required \
        802-1x.domain-match "$RADIUS_SERVER_NAME" \
        802-1x.phase1-auth-flags tls-1-0-disable,tls-1-1-disable,tls-1-2-disable,tls-1-3-enable \
        connection.autoconnect yes >/dev/null
    printf '    Added; it connects automatically when %s is in range\n' "$SSID"
else
    step 'NetworkManager not found; configure Wi-Fi manually'
    cat <<EOF
    wpa_supplicant network block:
      network={
          ssid="$SSID"
          key_mgmt=WPA-EAP WPA-EAP-SHA256
          ieee80211w=1
          eap=TLS
          identity="$DEVICE_ID"
          ca_cert="$DIR/root-ca.crt"
          client_cert="$DIR/cert.pem"
          private_key="$DIR/key.pem"
          domain_match="$RADIUS_SERVER_NAME"
          phase1="tls_disable_tlsv1_0=1 tls_disable_tlsv1_1=1 tls_disable_tlsv1_2=1 tls_disable_tlsv1_3=0"
      }
EOF
fi

# 5. Renewal ----------------------------------------------------------------------
if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
    step 'Scheduling certificate renewal'
    cat > /etc/systemd/system/cert-enrolment-renew.service <<EOF
[Unit]
Description=Renew the cert-enrolment device certificate
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
ExecStart=$RENEW
EOF
    cat > /etc/systemd/system/cert-enrolment-renew.timer <<'EOF'
[Unit]
Description=Check the cert-enrolment device certificate daily

[Timer]
OnBootSec=5min
OnCalendar=daily
RandomizedDelaySec=2h
Persistent=true

[Install]
WantedBy=timers.target
EOF
    chmod 644 /etc/systemd/system/cert-enrolment-renew.service /etc/systemd/system/cert-enrolment-renew.timer
    systemctl daemon-reload
    systemctl enable --now cert-enrolment-renew.timer >/dev/null
    printf '    Timer cert-enrolment-renew.timer checks daily; see journalctl -u cert-enrolment-renew\n'
else
    step 'systemd not found; schedule renewal yourself'
    printf '    Run %s daily as root, for example from cron.\n' "$RENEW"
fi

printf '\n%s is enrolled.\n' "$DEVICE_ID"
