#Requires -Version 5.1
#Requires -RunAsAdministrator
<#
    Enrols this computer as {{DEVICE_ID}} on the trusted Wi-Fi network.

    Generated by cert-enrolment. This script contains a single-use enrolment
    token that expires ten minutes after it was downloaded. Run it once, on
    the computer being enrolled, from an elevated PowerShell prompt:

        powershell -ExecutionPolicy Bypass -File .\enrol-{{LABEL}}.ps1

    It:
      1. trusts the network's Root CA (Local Computer, Trusted Root CAs)
      2. creates a private key in the TPM, which cannot be exported
      3. obtains a device certificate for {{DEVICE_ID}}
      4. adds a Wi-Fi profile for the trusted network that uses that certificate
      5. schedules certificate renewal (daily check, and at start-up)

    -AllowSoftwareKey uses a software key if the TPM cannot be used.
    -SkipWifi skips the Wi-Fi profile (for example, on a wired-only PC).
#>
[CmdletBinding()]
param(
    [switch] $AllowSoftwareKey,
    [switch] $SkipWifi
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 3

$DeviceId = '{{DEVICE_ID}}'
$CaUrl = '{{CA_URL}}'
$Token = '{{TOKEN}}'
$Ssid = '{{SSID}}'
$RadiusServerName = '{{RADIUS_SERVER_NAME}}'
$RootCaPem = @'
{{ROOT_CA_PEM}}
'@

$StateDir = Join-Path $env:ProgramData 'cert-enrolment'
$TaskName = 'cert-enrolment renewal'

# ---------------------------------------------------------------------------
# Shared with the renewal script, which is written out below.
# ---------------------------------------------------------------------------
$Common = @'
function Enable-ModernTls {
    $protocols = [Net.SecurityProtocolType]::Tls12
    if ([Enum]::GetNames([Net.SecurityProtocolType]) -contains 'Tls13') {
        $protocols = $protocols -bor [Net.SecurityProtocolType]::Tls13
    }
    [Net.ServicePointManager]::SecurityProtocol = $protocols
}

function ConvertFrom-Pem([string] $Pem) {
    $body = ($Pem -replace '-----[A-Z ]+-----', '') -replace '\s', ''
    New-Object System.Security.Cryptography.X509Certificates.X509Certificate2 (, [Convert]::FromBase64String($body))
}

# Creates a non-exportable P-256 key in the Local Computer context and a
# certificate request for it. The request stays pending so that
# certreq -accept can join the issued certificate to the key.
function New-DeviceRequest([string] $DeviceId, [string] $Provider, [string] $WorkDir) {
    Remove-PendingRequests -DeviceId $DeviceId
    $inf = Join-Path $WorkDir 'request.inf'
    $csr = Join-Path $WorkDir 'request.csr'
    @(
        '[Version]'
        'Signature = "$Windows NT$"'
        ''
        '[NewRequest]'
        "Subject = `"CN=$DeviceId`""
        'KeyAlgorithm = ECDSA_P256'
        'KeyLength = 256'
        "ProviderName = `"$Provider`""
        'MachineKeySet = TRUE'
        'Exportable = FALSE'
        'KeyUsage = 0x80'
        'RequestType = PKCS10'
        'HashAlgorithm = SHA256'
        "FriendlyName = `"cert-enrolment $DeviceId`""
        ''
        '[Extensions]'
        '2.5.29.17 = "{text}"'
        "_continue_ = `"dns=$DeviceId`""
    ) | Set-Content -Path $inf -Encoding ASCII

    $output = & certreq.exe -new -q -machine $inf $csr 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "certreq could not create a key with '$Provider': $($output -join ' ')"
    }

    # certreq labels the PEM "NEW CERTIFICATE REQUEST"; the CA expects the
    # standard label.
    (Get-Content -Raw $csr) -replace 'NEW CERTIFICATE REQUEST', 'CERTIFICATE REQUEST'
}

# Installs an issued certificate, joined to the key of its pending request,
# plus its intermediate CA. Returns the installed certificate.
function Install-DeviceCertificate($Response, [string] $DeviceId, [string] $WorkDir) {
    $crt = Join-Path $WorkDir 'device.crt'
    Set-Content -Path $crt -Value $Response.crt -Encoding ASCII
    $output = & certreq.exe -accept -q -machine $crt 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "certreq could not install the certificate: $($output -join ' ')"
    }

    if ($Response.ca) {
        $intermediate = ConvertFrom-Pem $Response.ca
        $store = New-Object System.Security.Cryptography.X509Certificates.X509Store('CA', 'LocalMachine')
        $store.Open('ReadWrite')
        try { $store.Add($intermediate) } finally { $store.Close() }
    }

    $issued = ConvertFrom-Pem $Response.crt
    $installed = Get-Item "Cert:\LocalMachine\My\$($issued.Thumbprint)"
    if (-not $installed.HasPrivateKey) {
        throw "The certificate for $DeviceId was installed without its private key."
    }
    $installed
}

# Removes other certificates for this device, and their keys.
function Remove-OtherDeviceCertificates([string] $DeviceId, [string] $Keep) {
    Get-ChildItem Cert:\LocalMachine\My |
        Where-Object { $_.Subject -eq "CN=$DeviceId" -and $_.Thumbprint -ne $Keep } |
        ForEach-Object { Remove-CertificateAndKey $_ }
}

function Get-StepCaError($ErrorRecord) {
    try { ($ErrorRecord.ErrorDetails.Message | ConvertFrom-Json).message } catch { $ErrorRecord.Exception.Message }
}

# True if the certificate authority answered, and so may have spent the
# token; false if it could not be reached at all.
function Test-CaAnswered($ErrorRecord) {
    $response = $ErrorRecord.Exception.PSObject.Properties['Response']
    [bool] ($response -and $response.Value)
}

# Removes pending certificate requests for this device, left by attempts
# that never received a certificate, together with their keys.
function Remove-PendingRequests([string] $DeviceId) {
    Get-ChildItem Cert:\LocalMachine\REQUEST -ErrorAction SilentlyContinue |
        Where-Object { $_.Subject -eq "CN=$DeviceId" } |
        ForEach-Object { Remove-CertificateAndKey $_ }
}

function Remove-CertificateAndKey($Certificate) {
    try {
        $key = [System.Security.Cryptography.X509Certificates.ECDsaCertificateExtensions]::GetECDsaPrivateKey($Certificate)
        if ($key -is [System.Security.Cryptography.ECDsaCng]) { $key.Key.Delete() }
    } catch {
        # The certificate is removed even if its key cannot be.
    }
    Remove-Item -Path $Certificate.PSPath
}
'@
. ([ScriptBlock]::Create($Common))

function Write-Step([string] $Message) { Write-Host "==> $Message" -ForegroundColor Cyan }

function Get-SpacedThumbprint($Certificate) {
    (($Certificate.Thumbprint.ToLower() -split '(..)') | Where-Object { $_ }) -join ' '
}

$build = [Environment]::OSVersion.Version.Build
if ($build -lt 22621) {
    Write-Warning "Windows build $build found. The network uses EAP over TLS 1.3, which Windows uses by default from Windows 11 22H2 (build 22621)."
}

Enable-ModernTls

# Check the certificate authority can be found before changing anything.
$caHost = ([Uri] $CaUrl).Host
try {
    [Net.Dns]::GetHostAddresses($caHost) | Out-Null
} catch {
    throw "This computer cannot resolve $caHost, so it cannot reach the certificate authority. Nothing has been changed. Check this computer's DNS settings, then run the script again; the enrolment token stays usable until ten minutes after download."
}

New-Item -ItemType Directory -Force -Path $StateDir | Out-Null
$work = Join-Path $env:TEMP ('cert-enrolment-' + [Guid]::NewGuid())
New-Item -ItemType Directory -Path $work | Out-Null

try {
    # 1. Root CA -------------------------------------------------------------
    Write-Step 'Trusting the network Root CA'
    $root = ConvertFrom-Pem $RootCaPem
    $rootStore = New-Object System.Security.Cryptography.X509Certificates.X509Store('Root', 'LocalMachine')
    $rootStore.Open('ReadWrite')
    try {
        if ($rootStore.Certificates.Find('FindByThumbprint', $root.Thumbprint, $false).Count -eq 0) {
            $rootStore.Add($root)
            Write-Host "    Added $($root.Subject)"
        } else {
            Write-Host "    Already trusted: $($root.Subject)"
        }
    } finally {
        $rootStore.Close()
    }
    Set-Content -Path (Join-Path $StateDir 'root-ca.crt') -Value $RootCaPem -Encoding ASCII

    # Now that the Root CA is trusted, check the CA answers over TLS.
    try {
        Invoke-RestMethod -Uri "$CaUrl/health" -UseBasicParsing | Out-Null
    } catch {
        throw "Could not reach the certificate authority at ${CaUrl}: $($_.Exception.Message) The enrolment token has not been used; run the script again within ten minutes of downloading it."
    }

    # 2. Key and certificate request -----------------------------------------
    Write-Step 'Creating the device key in the TPM'
    try {
        $csr = New-DeviceRequest -DeviceId $DeviceId -Provider 'Microsoft Platform Crypto Provider' -WorkDir $work
    } catch {
        if (-not $AllowSoftwareKey) {
            throw "The TPM could not be used: $($_.Exception.Message) Run again with -AllowSoftwareKey to use a software key instead."
        }
        Write-Warning 'The TPM could not be used; creating a non-exportable software key instead.'
        $csr = New-DeviceRequest -DeviceId $DeviceId -Provider 'Microsoft Software Key Storage Provider' -WorkDir $work
    }

    # 3. Certificate -----------------------------------------------------------
    Write-Step "Requesting a certificate for $DeviceId"
    $body = @{ csr = $csr; ott = $Token } | ConvertTo-Json -Compress
    try {
        $response = Invoke-RestMethod -Method Post -Uri "$CaUrl/1.0/sign" -ContentType 'application/json' -Body $body -UseBasicParsing
    } catch {
        Remove-PendingRequests -DeviceId $DeviceId
        if (Test-CaAnswered $_) {
            throw "The certificate authority refused the request: $(Get-StepCaError $_) Enrolment tokens work once and expire ten minutes after download; download a new script from the Enrol page."
        }
        throw "Could not reach the certificate authority at ${CaUrl}: $($_.Exception.Message) The enrolment token has not been used; run the script again within ten minutes of downloading it."
    }
    $certificate = Install-DeviceCertificate -Response $response -DeviceId $DeviceId -WorkDir $work
    Remove-OtherDeviceCertificates -DeviceId $DeviceId -Keep $certificate.Thumbprint
    Write-Host "    Installed; valid until $($certificate.NotAfter)"

    # 4. Wi-Fi profile ---------------------------------------------------------
    if ($SkipWifi) {
        Write-Step 'Skipping the Wi-Fi profile'
    } elseif (-not (Get-Service -Name WlanSvc -ErrorAction SilentlyContinue)) {
        Write-Step 'No Wi-Fi on this computer; skipping the Wi-Fi profile'
    } else {
        Write-Step "Adding the Wi-Fi profile for $Ssid"
        $intermediate = ConvertFrom-Pem $response.ca
        $name = [Security.SecurityElement]::Escape($Ssid)
        $rootHash = Get-SpacedThumbprint $root
        $issuerHash = Get-SpacedThumbprint $intermediate
        $profileXml = @"
<?xml version="1.0"?>
<WLANProfile xmlns="http://www.microsoft.com/networking/WLAN/profile/v1">
  <name>$name</name>
  <SSIDConfig>
    <SSID><name>$name</name></SSID>
    <nonBroadcast>false</nonBroadcast>
  </SSIDConfig>
  <connectionType>ESS</connectionType>
  <connectionMode>auto</connectionMode>
  <autoSwitch>false</autoSwitch>
  <MSM>
    <security>
      <authEncryption>
        <authentication>WPA3ENT</authentication>
        <encryption>AES</encryption>
        <useOneX>true</useOneX>
      </authEncryption>
      <OneX xmlns="http://www.microsoft.com/networking/OneX/v1">
        <authMode>machine</authMode>
        <EAPConfig>
          <EapHostConfig xmlns="http://www.microsoft.com/provisioning/EapHostConfig">
            <EapMethod>
              <Type xmlns="http://www.microsoft.com/provisioning/EapCommon">13</Type>
              <VendorId xmlns="http://www.microsoft.com/provisioning/EapCommon">0</VendorId>
              <VendorType xmlns="http://www.microsoft.com/provisioning/EapCommon">0</VendorType>
              <AuthorId xmlns="http://www.microsoft.com/provisioning/EapCommon">0</AuthorId>
            </EapMethod>
            <Config xmlns="http://www.microsoft.com/provisioning/EapHostConfig">
              <Eap xmlns="http://www.microsoft.com/provisioning/BaseEapConnectionPropertiesV1">
                <Type>13</Type>
                <EapType xmlns="http://www.microsoft.com/provisioning/EapTlsConnectionPropertiesV1">
                  <CredentialsSource>
                    <CertificateStore>
                      <SimpleCertSelection>true</SimpleCertSelection>
                    </CertificateStore>
                  </CredentialsSource>
                  <ServerValidation>
                    <DisableUserPromptForServerValidation>true</DisableUserPromptForServerValidation>
                    <ServerNames>$RadiusServerName</ServerNames>
                    <TrustedRootCA>$rootHash</TrustedRootCA>
                  </ServerValidation>
                  <DifferentUsername>false</DifferentUsername>
                  <PerformServerValidation xmlns="http://www.microsoft.com/provisioning/EapTlsConnectionPropertiesV2">true</PerformServerValidation>
                  <AcceptServerName xmlns="http://www.microsoft.com/provisioning/EapTlsConnectionPropertiesV2">true</AcceptServerName>
                  <TLSExtensions xmlns="http://www.microsoft.com/provisioning/EapTlsConnectionPropertiesV2">
                    <FilteringInfo xmlns="http://www.microsoft.com/provisioning/EapTlsConnectionPropertiesV3">
                      <CAHashList Enabled="true">
                        <IssuerHash>$issuerHash</IssuerHash>
                      </CAHashList>
                    </FilteringInfo>
                  </TLSExtensions>
                </EapType>
              </Eap>
            </Config>
          </EapHostConfig>
        </EAPConfig>
      </OneX>
    </security>
  </MSM>
</WLANProfile>
"@
        $profileFile = Join-Path $work 'wifi-profile.xml'
        Set-Content -Path $profileFile -Value $profileXml -Encoding UTF8
        $output = & netsh.exe wlan add profile filename="$profileFile" user=all 2>&1
        if ($LASTEXITCODE -ne 0) {
            throw "netsh could not add the Wi-Fi profile: $($output -join ' ')"
        }
        Write-Host "    Added; it connects automatically when $Ssid is in range"
    }

    # 5. Renewal -----------------------------------------------------------------
    Write-Step 'Scheduling certificate renewal'
    $renewScript = Join-Path $StateDir 'renew.ps1'
    $renewBody = @"
# Renews the cert-enrolment device certificate for $DeviceId when two thirds
# of its lifetime has passed. Run daily and at start-up by the scheduled task
# '$TaskName'. Each renewal creates a new TPM key (step-ca rekey), proving
# identity with the current certificate.
`$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 3
`$DeviceId = '$DeviceId'
`$CaUrl = '$CaUrl'
`$AllowSoftwareKey = `$$([bool] $AllowSoftwareKey)
`$Log = Join-Path `$PSScriptRoot 'renew.log'
function Write-Log([string] `$Message) {
    `$lines = @(if (Test-Path `$Log) { Get-Content `$Log -Tail 199 })
    (`$lines + "`$(Get-Date -Format s) `$Message") | Set-Content -Path `$Log -Encoding ASCII
}
"@ + "`r`n" + $Common + "`r`n" + @'
try {
    Enable-ModernTls
    $current = Get-ChildItem Cert:\LocalMachine\My |
        Where-Object { $_.Subject -eq "CN=$DeviceId" -and $_.HasPrivateKey } |
        Sort-Object NotAfter -Descending | Select-Object -First 1
    if (-not $current) { Write-Log "No certificate for $DeviceId; enrol this computer again."; exit 1 }
    if ((Get-Date) -gt $current.NotAfter) { Write-Log "The certificate expired on $($current.NotAfter); enrol this computer again."; exit 1 }

    $due = $current.NotBefore.AddTicks([long](($current.NotAfter - $current.NotBefore).Ticks * 2 / 3))
    if ((Get-Date) -lt $due) { Write-Log "Valid until $($current.NotAfter); renewal due $due."; exit 0 }

    $work = Join-Path $env:TEMP ('cert-enrolment-' + [Guid]::NewGuid())
    New-Item -ItemType Directory -Path $work | Out-Null
    try {
        try {
            $csr = New-DeviceRequest -DeviceId $DeviceId -Provider 'Microsoft Platform Crypto Provider' -WorkDir $work
        } catch {
            if (-not $AllowSoftwareKey) { throw }
            $csr = New-DeviceRequest -DeviceId $DeviceId -Provider 'Microsoft Software Key Storage Provider' -WorkDir $work
        }
        $body = @{ csr = $csr } | ConvertTo-Json -Compress
        try {
            $response = Invoke-RestMethod -Method Post -Uri "$CaUrl/1.0/rekey" -Certificate $current -ContentType 'application/json' -Body $body -UseBasicParsing
        } catch {
            Remove-PendingRequests -DeviceId $DeviceId
            if (Test-CaAnswered $_) { throw "The certificate authority refused renewal: $(Get-StepCaError $_)" }
            throw "Could not reach the certificate authority at ${CaUrl}: $($_.Exception.Message) Will retry at the next check."
        }
        $renewed = Install-DeviceCertificate -Response $response -DeviceId $DeviceId -WorkDir $work
        Remove-OtherDeviceCertificates -DeviceId $DeviceId -Keep $renewed.Thumbprint
        Write-Log "Renewed; the new certificate is valid until $($renewed.NotAfter)."
    } finally {
        Remove-Item -Recurse -Force -Path $work -ErrorAction SilentlyContinue
    }
} catch {
    Write-Log "Renewal failed: $($_.Exception.Message)"
    exit 1
}
'@
    Set-Content -Path $renewScript -Value $renewBody -Encoding ASCII

    # Only SYSTEM and Administrators may change what the task runs.
    $acl = New-Object System.Security.AccessControl.DirectorySecurity
    $acl.SetAccessRuleProtection($true, $false)
    foreach ($sid in 'S-1-5-18', 'S-1-5-32-544') {
        $identity = (New-Object System.Security.Principal.SecurityIdentifier($sid))
        $rule = New-Object System.Security.AccessControl.FileSystemAccessRule($identity, 'FullControl', 'ContainerInherit,ObjectInherit', 'None', 'Allow')
        $acl.AddAccessRule($rule)
    }
    Set-Acl -Path $StateDir -AclObject $acl

    $action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -NonInteractive -ExecutionPolicy Bypass -File `"$renewScript`""
    $triggers = @(
        (New-ScheduledTaskTrigger -Daily -At 3am -RandomDelay (New-TimeSpan -Hours 2)),
        (New-ScheduledTaskTrigger -AtStartup)
    )
    $principal = New-ScheduledTaskPrincipal -UserId 'S-1-5-18' -LogonType ServiceAccount -RunLevel Highest
    $settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -ExecutionTimeLimit (New-TimeSpan -Minutes 10)
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $triggers -Principal $principal -Settings $settings -Force | Out-Null
    Write-Host "    Task '$TaskName' checks daily; log: $(Join-Path $StateDir 'renew.log')"

    Write-Host ''
    Write-Host "$DeviceId is enrolled." -ForegroundColor Green
} finally {
    Remove-Item -Recurse -Force -Path $work -ErrorAction SilentlyContinue
}
